services:
  app:
    pull_policy: if_not_present
    build: 
      context: .
    restart: unless-stopped
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./templates:/etc/nginx/templates
      - ./certs:/certs
      - /home/ubuntu/dev/movies:/movies
